version: '3.8'

services:
  real-esrgan-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: real-esrgan-cpu-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - esrgan-network

networks:
  esrgan-network:
    driver: bridge